config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  resources :authors
  resources :books

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
  validates :name, presence: true

  def to_s
    name
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  validates :title, :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/_form.html.slim
= simple_form_for(@author) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/authors/edit.html.slim
h1 Editing author

== render 'form'

= link_to 'Show', @author
'|
= link_to 'Back', authors_path

app/views/authors/index.html.slim
h1 Listing authors

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @authors.each do |author|
      tr
        td = author.name
        td = link_to 'Show', author
        td = link_to 'Edit', edit_author_path(author)
        td = link_to 'Destroy', author, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Author', new_author_path

app/views/authors/new.html.slim
h1 New author

== render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.slim
p#notice = notice

p
  strong Name:
  = @author.name

= link_to 'Edit', edit_author_path(@author)
'|
= link_to 'Back', authors_path

app/views/books/_form.html.slim
= simple_form_for(@book) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.association :author

  .form-actions
    = f.button :submit

app/views/books/edit.html.slim
h1 Editing book

== render 'form'

= link_to 'Show', @book
'|
= link_to 'Back', books_path

app/views/books/index.html.slim
h1 Listing books

table
  thead
    tr
      th Title
      th Author
      th
      th
      th

  tbody
    - @books.each do |book|
      tr
        td = book.title
        td = book.author
        td = link_to 'Show', book
        td = link_to 'Edit', edit_book_path(book)
        td = link_to 'Destroy', book, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Book', new_book_path

app/views/books/new.html.slim
h1 New book

== render 'form'

= link_to 'Back', books_path

app/views/books/show.html.slim
p#notice = notice

p
  strong Title:
  = @book.title
p
  strong Author:
  = @book.author

= link_to 'Edit', edit_book_path(@book)
'|
= link_to 'Back', books_path

app/views/home/index.html.slim
.books_widget
  div
    .col
      button.lucky мне повезёт!
    .col
      .author
        label
          | имя автора
          br
          select
    .col
      .book
        label
          | произведение
          br
          select
  p.message

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | BooksCatalog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    ul
      li = link_to 'Home', root_path
      li = link_to 'Authors', authors_path
      li = link_to 'Books', books_path
    = yield